### ISSUE TITLE
Skip table manipulation instruction during init

### ISSUE THREAD

**Issue by dbezhetskov** [bytecodealliance/wizer#102]
Hey, is it possible to skip table.grow, table.set and other table manipulation instructions during initialization phase?
I want to add missing functions to the table later.

**Comment by fitzgen** [comment]
A philosophical line that Wizer draws in the sand is that it matches/abides/implements Wasm semantics. It is "just" an otherwise transparent optimization. That means that we do not change the program during initialization.

I would suggest refactoring your program such that these table operations don't appear in initialization and you can do the grow and fill later (like you would otherwise have to anyways).
