### ISSUE TITLE
Unexport `_initialize` from wizened WASI reactors

### ISSUE THREAD

**Issue by TerrorJack** [bytecodealliance/wizer#35]
The `wizer.initialize` function is preserved in the snapshotted wasm module, but it's not expected to be called again, so it would be nice to add an option to strip the initialize function export, so that further optimization passes in other tools like `wasm-opt` can remove the unused initialization logic completely.

**Comment by fitzgen** [comment]
It should already be the case that the initialization function is not exported in the rewritten Wasm:

* https://github.com/bytecodealliance/wizer/blob/main/src/rewrite.rs#L137-L139
* https://github.com/bytecodealliance/wizer/blob/main/src/rewrite.rs#L418-L420

If you are observing otherwise, can you provide an input Wasm and the exact steps to reproduce?

**Comment by TerrorJack** [comment]
Apologies for slow response. `wizer.initialize` is stripped, but `_initialize` (in case of a WASI reactor) is preserved, and `_initialize` should be stripped as well, since `wizer` should have already invoked it once when snapshotting.
